fail_fast: false
repos:
  - repo: local
    hooks:
      - id: black
        name: Black
        entry: black src
        pass_filenames: false
        language: system
      - id: isort
        name: isort
        entry: isort src
        pass_filenames: false
        language: system
      - id: ruff
        name: ruff
        entry: ruff
        files: src
        language: python
        "types": [ python ]
      - id: pytest
        name: tests
        entry: pytest
        pass_filenames: false
        language: system