name: PR Checks
on: pull_request
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.4
      - name: Install Just
        uses: extractions/setup-just@v1
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.13
      - name: Install Dependencies
        run: poetry install
      - name: Pull docker images ahead of tests
        run: docker pull postgres:14
      - name: Run Tests
        run: just test